name: Capture Screenshots
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install Dependencies
        run: npm install

      - name: Run Screenshot Script
        run: node captureScreenshots.js

      - name: Check git diff
        run: |
          ls -l *.png
          git status
          git diff

      - name: Commit and Push Screenshot main
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add generated screenshot
          force-add: true
          force-push: true
          files: arsolj.png
      
